tap "hashicorp/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "thoughtbot/formulae"
brew "ack"
brew "antigen"
brew "asdf"
brew "cocoapods"
brew "dnsmasq", restart_service: true
brew "docker", link: false
brew "fd"
brew "fzf"
brew "gawk"
brew "gdal"
brew "geoip"
brew "git"
brew "git-flow"
brew "gnu-sed"
brew "gnupg"
brew "go"
brew "lua"
brew "httpie"
brew "ios-deploy"
brew "libusbmuxd", args: ["HEAD"]
brew "libimobiledevice"
brew "ios-webkit-debug-proxy"
brew "jq"
brew "lastpass-cli"
brew "lazygit"
brew "libiconv"
brew "libxslt"
brew "lua@5.1"
brew "luarocks"
brew "mas"
brew "mysql@5.7", restart_service: true, link: true
brew "tree-sitter"
brew "neovim"
brew "nginx"
brew "php"
brew "php@7.3"
brew "pv"
brew "r"
brew "ripgrep"
brew "ruby"
brew "rust"
brew "stow"
brew "stylua"
brew "terraform"
brew "the_silver_searcher"
brew "tree"
brew "udunits"
brew "vint", link: false
brew "watchman"
brew "wget"
brew "youtube-dl"
brew "hashicorp/tap/terraform-ls"
brew "thoughtbot/formulae/rcm"
cask "1password"
cask "alfred"
cask "browserosaurus"
cask "cleanshot"
cask "cron"
cask "dbeaver-community"
cask "discord"
cask "disk-inventory-x"
cask "docker"
cask "dropbox"
cask "fig"
cask "firefox"
cask "flipper"
cask "font-cascadia"
cask "font-cascadia-mono"
cask "font-fira-code"
cask "font-fira-code-nerd-font"
cask "font-fira-mono"
cask "font-hack-nerd-font"
cask "github"
cask "google-backup-and-sync"
cask "google-chrome"
cask "google-cloud-sdk"
cask "grammarly"
cask "insomnia"
cask "itau"
cask "iterm2"
cask "kitty"
cask "logitech-options"
cask "megasync"
cask "miro"
cask "mongodb-compass"
cask "ngrok"
cask "notion"
cask "postman"
cask "provisionql"
cask "qlcolorcode"
cask "qlmarkdown"
cask "quicklook-csv"
cask "quicklook-json"
cask "raycast"
cask "rectangle"
cask "slack"
cask "sourcetree"
cask "spotify"
cask "sublime-text"
cask "the-unarchiver"
cask "transmission"
cask "vanilla"
cask "visual-studio-code"
cask "vlc"
cask "whatsapp"
cask "zoom"
mas "Amphetamine", id: 937984704
mas "Dato", id: 1470584107
mas "DuckDuckGo Privacy Essentials", id: 1482920575
mas "Ghostery – Privacy Ad Blocker", id: 1436953057
mas "GoodNotes", id: 1444383602
mas "Grammarly for Safari", id: 1462114288
mas "NordVPN", id: 905953485
