tap "dart-lang/dart"
tap "facebook/fb"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "thoughtbot/formulae"
brew "ack"
brew "antigen"
brew "asdf"
brew "awscli"
brew "cocoapods"
brew "composer"
brew "dnsmasq", restart_service: true
brew "fd"
brew "fzf"
brew "libxml2"
brew "gdal"
brew "geoip"
brew "git"
brew "git-flow"
brew "gnupg"
brew "httpie"
brew "ios-deploy"
brew "libusbmuxd", args: ["HEAD"]
brew "libimobiledevice"
brew "ios-webkit-debug-proxy"
brew "lastpass-cli"
brew "libiconv"
brew "libxslt"
brew "mas"
brew "mysql@5.7", restart_service: true, link: true
brew "neovim"
brew "nginx"
brew "openjdk"
brew "php", restart_service: true
brew "php@7.1"
brew "php@7.2"
brew "php@7.3"
brew "pv"
brew "r"
brew "ripgrep"
brew "ruby"
brew "the_silver_searcher"
brew "tree"
brew "udunits"
brew "watchman"
brew "wget"
brew "youtube-dl"
brew "facebook/fb/idb-companion"
brew "thoughtbot/formulae/rcm"
cask "alfred"
cask "android-file-transfer"
cask "android-studio"
cask "browserosaurus"
cask "clickup"
cask "clockify"
cask "dbeaver-community"
cask "discord"
cask "disk-inventory-x"
cask "docker"
cask "dozer"
cask "firefox"
cask "flipper"
cask "font-cascadia"
cask "font-cascadia-mono"
cask "font-cascadia-nerd-font-mono"
cask "font-fira-code"
cask "font-hack-nerd-font"
cask "gimp"
cask "github"
cask "google-backup-and-sync"
cask "google-chrome"
cask "google-cloud-sdk"
cask "grammarly"
cask "insomnia"
cask "istat-menus"
cask "itau"
cask "kitty"
cask "macdown"
cask "megasync"
cask "mongodb-compass"
cask "ngrok"
cask "postman"
cask "provisionql"
cask "qlcolorcode"
cask "qlmarkdown"
cask "quicklook-csv"
cask "quicklook-json"
cask "rectangle"
cask "slack"
cask "spotify"
cask "sublime-text"
cask "transmission"
cask "visual-studio-code"
cask "vlc"
cask "whatsapp"
cask "yt-music"
cask "zoomus"
mas "Amphetamine", id: 937984704
mas "Dato", id: 1470584107
mas "LastPass", id: 926036361
mas "NordVPN IKE", id: 1116599239
mas "Transporter", id: 1450874784
mas "Xcode", id: 497799835
